AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: This SAM template provisions AWS SNS Topic and SQS Queues for Operations processing.

Parameters:
  EventsProcessEndpoint:
    Type: String
    Description: Public HTTPS endpoint that receives SNS messages (e.g. https://api.example.com/api/v1/events/operations/closed)
  EventsOperationAttachmentCategorizeEndpoint:
    Type: String
    Description: Public HTTPS endpoint that receives SNS messages

Resources:
  operationMoveToNew:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-move-to-new"

  operationClosed:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-closed"

  operationClosedSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref operationClosed
      Protocol: https
      Endpoint: !Ref EventsProcessEndpoint

  operationMoveToInVerification:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-move-to-in-verification"

  operationAttachmentCreated:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-operation-attachment-created"

  operationAttachmentCreatedSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref operationAttachmentCreated
      Protocol: https
      Endpoint: !Ref EventsOperationAttachmentCategorizeEndpoint

  RobotOperacionesDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-robot-operaciones-dlq"

  RobotOperacionesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-robot-operaciones-queue"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt RobotOperacionesDLQ.Arn
        maxReceiveCount: 3
  RobotOperacionesQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref operationMoveToNew
      Protocol: sqs
      Endpoint: !GetAtt RobotOperacionesQueue.Arn

  RobotOperacionesQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref RobotOperacionesQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: sqs:SendMessage
            Resource: !GetAtt RobotOperacionesQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref operationMoveToNew
