from typing import Any, Protocol

from src.domain.models import AuthToken


class S3Interface(Protocol):
    """Interface for S3 storage operations."""

    def upload_file(
        self, file_obj: Any, key: str, content_type: str | None = None
    ) -> str: ...

    def download_file(self, key: str) -> bytes: ...

    def get_file_url(self, key: str) -> str: ...

    def file_exists(self, bucket_name: str, object_name: str) -> bool: ...


class OperacionesInterface(Protocol):
    """Interface for database operations related to 'operaciones'."""

    def generar_id_operacion(self, email_usuario: str) -> str: ...

    def get_operaciones(self, gmail: str) -> list[dict]: ...

    def get_facturas(self, id_operacion: str) -> list[dict]: ...

    def create_operacion(self, operacion_data: dict, id_op: str) -> str: ...

    def update_estado(self, id_operacion: str, nuevo_estado: str) -> None: ...

    def factura_duplicada(self, numero_factura: str, ruc_deudor: str) -> str | None: ...


class ContactosInterface(Protocol):
    """Interface for database operations related to 'contactos'."""

    def get_contactos(self, ruc_deudor: str) -> list[dict]: ...

    def add_correo(self, ruc_deudor: str, gmail: str) -> None: ...

    def delete_correo(self, ruc_deudor: str, gmail: str) -> None: ...


class AuthInterface(Protocol):
    """Contrato para Auth Seguridad"""

    def verify_token(self, token: str) -> AuthToken: ...

    def find_by_email(self, email): ...

    def create(self, email, nombre: str): ...
